version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./src/main/js/work-demo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
